[package]
name = "yas-backend"
version = "1.0.0"
edition = "2018"
publish = false

[dependencies]
actix-web = "3.3.2"
async-std = "1.8.0"
rand = "0.7.3"
serde = "1.0.118"
serde_derive = "1.0.118"
serde_json = "1.0.60"
