[package]
name = "yas-backend"
version = "1.0.0"
edition = "2018"
publish = false

[dependencies]
rand = "0.7.2"
rocket = "0.4.2"
serde = "1.0.103"
serde_json = "1.0.42"
serde_derive = "1.0.103"

[dependencies.rocket_contrib]
rocket_contrib = "0.4.2"
default-features = false
features = ["json"]
