[package]
name = "yas-backend"
version = "1.0.0"
edition = "2018"
publish = false

[dependencies]
actix-rt = "1.0.0"
actix-web = "2.0.0"
async-std = "1.5.0"
rand = "0.7.3"
serde = "1.0.104"
serde_json = "1.0.48"
serde_derive = "1.0.104"
