name: Yas Shop CI

on: [push]

jobs:
  build-frontend:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 15
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: npm install, test, and build
        working-directory: ./yas-frontend
        run: |
          npm install
          npm run test
          npm run build
        env:
          CI: true

  build-backend:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true
      - name: Build
        working-directory: ./yas-backend
        run: cargo build --verbose
      - name: Run tests
        working-directory: ./yas-backend
        run: cargo test --verbose