name: Yas-Shop CI

on: [push]

jobs:
  build-frontend:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install, test, and build
        run: |
          ./yas-frontend/npm install
          ./yas-frontend/npm run test
          ./yas-frontend/npm run build
        env:
          CI: true

  build-backend:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: ./yas-backend/cargo build --verbose
      - name: Run tests
        run: ./yas-backend/cargo test --verbose